[package]
name = "qemu-run"
version = "0.2.1"
authors = ["Toru Ogawa <Hakuyume@users.noreply.github.com>"]

[dependencies]
docopt = "0.8"
rand = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.7"
sha2 = "0.7"
