[package]
name = "qemu-run"
version = "0.2.6"
authors = ["Toru Ogawa <Hakuyume@users.noreply.github.com>"]
edition = "2018"

[dependencies]
docopt = "1,1"
libusb = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
sha2 = "0.8"
